In [17]:
import numpy as np

arr = np.arange(24).reshape((4, 2, 3))
print(arr)

x1=arr.reshape(arr.shape[0],-1).T
x2=arr.reshape(arr.shape[1],-1).T
print("x1:\n"+str(x1))

print("x2:\n"+str(x2))



[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]]]
x1:
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
x2:
[[ 0 12]
 [ 1 13]
 [ 2 14]
 [ 3 15]
 [ 4 16]
 [ 5 17]
 [ 6 18]
 [ 7 19]
 [ 8 20]
 [ 9 21]
 [10 22]
 [11 23]]
